# Generated by Django 3.2.2 on 2022-05-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20220511_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.PositiveSmallIntegerField(help_text='Duración de la Carrera o Curso en hs', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='Nombre de la Materia o Curso', max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', help_text='Dirección', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='file_number',
            field=models.CharField(help_text='Número de Legajo/Expediente o Libreta Universitaria: xxxxxxx', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Nombre', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(help_text='Apellido', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='', help_text='Número de teléfono', max_length=64),
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('career_name', models.CharField(help_text='Nombre de la Carrera/Curso', max_length=128, verbose_name='name')),
                ('year_enrollment', models.CharField(help_text='Año de Inscripción a la Carrera: YYYY', max_length=4, verbose_name='enrolled')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.student')),
            ],
            options={
                'db_table': 'careers',
            },
        ),
    ]
