# Generated by Django 3.2.2 on 2022-05-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20220511_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='numtime_taken_course',
            field=models.PositiveSmallIntegerField(default='0', help_text='Número de veces que cursó la materia.'),
        ),
        migrations.AlterField(
            model_name='career',
            name='course',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='leads.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.PositiveSmallIntegerField(help_text='Duración de la Carrera/Curso en hs', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='Nombre de la Materia/Curso', max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='passed',
            field=models.BooleanField(default=False, help_text='Aprobó la Materia/Curso'),
        ),
    ]
